nome = str(input("Digite seu nome completo: ")).strip()
print('O Seu nome em mauiúsculo será: {}'.format(nome.upper()))
print('O seu nome em minusculo será: {}'.format(nome.lower()))
print('O Seu nome possui {} letras.'.format(len(''.join(nome.split()))))
no = nome.split()
print('O primeiro nome possui {} letras'.format(len(no[0])))
